"use client";

import { ChangeEvent, FormEvent, useCallback, useEffect, useMemo, useRef, useState } from "react";
import { DayPlan, EventItem, Expense, initialDays } from "./trip-data";
import { AttractionGuide, guideForEvent, initialGuides } from "./attraction-guides";
import { FoodGuide, foodGuides } from "./food-guides";

type Ticket = { id:string; eventId:string; name:string; number:string; fileName?:string; fileType?:string; fileData?:string };
type TicketPreview = { data:string; type:string; name:string };
type DayStyle = "orchid"|"garden"|"peranakan"|"sunrise"|"marina";
type HeroConfig = { title:string; kicker:string; tripDates:string; hotel:string; backgroundImage?:string; styleTheme?:DayStyle };
type SharedState = { hero:HeroConfig; days:DayPlan[]; version:number };
type AppData = SharedState & { tickets:Ticket[]; expenses:Expense[] };
type LocalRecord = { base:SharedState; local:Pick<SharedState,"hero"|"days">; tickets:Ticket[]; expenses:Expense[] };
type Tab = "plan" | "attractions" | "expenses" | "edit";

const defaultHero:HeroConfig = { title:"獅城漫遊", kicker:"SINGAPORE · 5 DAYS", tripDates:"26–30 AUG 2026", hotel:"Hotel Faber Park", styleTheme:"peranakan" };
const DAY_STYLE_OPTIONS:{id:DayStyle;name:string;description:string;sample:string}[] = [
  {id:"peranakan",name:"娘惹彩磚",description:"土耳其藍、珊瑚粉與活潑幾何感",sample:"NYONYA"},
  {id:"orchid",name:"胡姬花園",description:"蘭花粉、象牙白與花瓣幾何紋",sample:"ORCHID"},
  {id:"garden",name:"城市花園",description:"嫩葉綠、薄荷白與葉片幾何紋",sample:"GARDEN"},
  {id:"sunrise",name:"南洋晨光",description:"芒果黃、蜜桃橘與溫暖圓潤字體",sample:"SUNRISE"},
  {id:"marina",name:"濱海晴空",description:"天空藍、水藍與俐落現代字體",sample:"MARINA"},
];
const FONT_SCALE_KEY = "singapore-travel-font-scale";
const defaultShared:SharedState = { hero:defaultHero, days:initialDays, version:0 };
const emptyData:AppData = { ...defaultShared, tickets:[], expenses:[] };
const money = new Intl.NumberFormat("zh-TW", { style:"currency", currency:"SGD" });
const dateLabel = (value:string) => new Intl.DateTimeFormat("zh-TW", { month:"numeric", day:"numeric" }).format(new Date(`${value}T12:00:00`));
const localDateKey = (date = new Date()) => `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`;
const chooseInitialDate = (days:DayPlan[]) => { const today=localDateKey(); return days.find(day=>day.date===today)?.date || days.find(day=>day.date>today)?.date || days.at(-1)?.date || today; };
const getStartMinutes = (time:string) => { const match=time.match(/(\d{1,2}):(\d{2})/); return match ? Number(match[1])*60+Number(match[2]) : 0; };
const same = (a:unknown,b:unknown) => JSON.stringify(a)===JSON.stringify(b);

function mergeObject<T extends Record<string,unknown>>(oldBase:T,local:T,newBase:T):T {
  const result={...newBase} as T;
  for(const key of Object.keys(local) as (keyof T)[]) if(!same(local[key],oldBase[key])) result[key]=local[key];
  return result;
}
function mergeEvents(oldEvents:EventItem[],localEvents:EventItem[],newEvents:EventItem[]){
  const oldMap=new Map(oldEvents.map(x=>[x.id,x])), localMap=new Map(localEvents.map(x=>[x.id,x]));
  const merged=newEvents.flatMap(next=>{const old=oldMap.get(next.id),local=localMap.get(next.id);if(old&&!local)return [];if(!old||!local)return [next];return [mergeObject(old as unknown as Record<string,unknown>,local as unknown as Record<string,unknown>,next as unknown as Record<string,unknown>) as unknown as EventItem];});
  return [...merged,...localEvents.filter(x=>!oldMap.has(x.id)&&!newEvents.some(n=>n.id===x.id))].sort((a,b)=>getStartMinutes(a.time)-getStartMinutes(b.time));
}
function mergeShared(oldBase:SharedState,local:Pick<SharedState,"hero"|"days">,next:SharedState){
  const oldDays=new Map(oldBase.days.map(x=>[x.id,x])), localDays=new Map(local.days.map(x=>[x.id,x]));
  const days=next.days.flatMap(nextDay=>{const old=oldDays.get(nextDay.id),mine=localDays.get(nextDay.id);if(old&&!mine)return [];if(!old||!mine)return [nextDay];const merged=mergeObject(old as unknown as Record<string,unknown>,mine as unknown as Record<string,unknown>,nextDay as unknown as Record<string,unknown>) as unknown as DayPlan;merged.events=mergeEvents(old.events,mine.events,nextDay.events);return [merged];});
  days.push(...local.days.filter(x=>!oldDays.has(x.id)&&!next.days.some(n=>n.id===x.id)));
  return { hero:mergeObject(oldBase.hero as unknown as Record<string,unknown>,local.hero as unknown as Record<string,unknown>,next.hero as unknown as Record<string,unknown>) as unknown as HeroConfig, days };
}

function openDb(){return new Promise<IDBDatabase>((resolve,reject)=>{const request=indexedDB.open("singapore-travel-device",1);request.onupgradeneeded=()=>request.result.createObjectStore("data");request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}
async function localGet(){const db=await openDb();return new Promise<LocalRecord|undefined>((resolve,reject)=>{const tx=db.transaction("data","readonly");const request=tx.objectStore("data").get("device");request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}
async function localPut(value:LocalRecord){const db=await openDb();return new Promise<void>((resolve,reject)=>{const tx=db.transaction("data","readwrite");tx.objectStore("data").put(value,"device");tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);});}
function fileToData(file:File){return new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(reader.error);reader.readAsDataURL(file);});}

export default function Home(){
  const [data,setData]=useState<AppData>(emptyData),[selectedDate,setSelectedDate]=useState(chooseInitialDate(initialDays));
  const [tab,setTab]=useState<Tab>("plan"),[editingId,setEditingId]=useState<string|null>(null),[dirty,setDirty]=useState(false),[saving,setSaving]=useState(false);
  const [ticketEvent,setTicketEvent]=useState<EventItem|null>(null),[ticketPreview,setTicketPreview]=useState<TicketPreview|null>(null),[styleEditorOpen,setStyleEditorOpen]=useState(false),[fontEditorOpen,setFontEditorOpen]=useState(false),[heroEditorOpen,setHeroEditorOpen]=useState(false),[loginOpen,setLoginOpen]=useState(false),[toast,setToast]=useState("");
  const [guideId,setGuideId]=useState<string|null>(null);
  const [isAdmin,setIsAdmin]=useState(false),[configured,setConfigured]=useState(true),[ready,setReady]=useState(false);
  const [fontScale,setFontScale]=useState(1);
  const eventRefs=useRef<Record<string,HTMLDetailsElement|null>>({}), sharedRef=useRef<SharedState>(defaultShared), overlayRef=useRef<Pick<SharedState,"hero"|"days">>({hero:defaultHero,days:initialDays});
  const day=data.days.find(item=>item.date===selectedDate)||data.days[0],today=localDateKey();
  const flash=(message:string)=>{setToast(message);window.setTimeout(()=>setToast(""),2400);};

  const load=useCallback(async(silent=false)=>{try{
    const [stateResponse,sessionResponse,record]=await Promise.all([fetch("/api/state",{cache:"no-store"}),fetch("/api/auth/session",{cache:"no-store"}),localGet().catch(()=>undefined)]);
    const remoteRaw=await stateResponse.json() as Partial<SharedState>; const remote:SharedState=remoteRaw.days?.length&&remoteRaw.hero?{hero:remoteRaw.hero,days:remoteRaw.days,version:remoteRaw.version||0}:defaultShared;
    const session=await sessionResponse.json() as {admin:boolean;configured:boolean}; sharedRef.current=remote;setIsAdmin(session.admin);setConfigured(session.configured);
    const local=record?mergeShared(record.base,record.local,remote):{hero:remote.hero,days:remote.days};overlayRef.current=record?.local||local;
    setData({...remote,...(session.admin?{hero:remote.hero,days:remote.days}:local),tickets:record?.tickets||[],expenses:record?.expenses||[]});setReady(true);
  }catch{if(!silent)flash("目前使用離線資料");setReady(true);}},[]);
  useEffect(()=>{load();},[load]);
  useEffect(()=>{const saved=Number(localStorage.getItem(FONT_SCALE_KEY));if(saved>=.9&&saved<=1.3)setFontScale(saved);},[]);
  useEffect(()=>{if(!history.state?.travelApp)history.replaceState({...history.state,travelApp:true,travelTab:"plan"},"");const handleBack=(event:PopStateEvent)=>{const state=event.state||{};setTicketPreview(null);if(state.travelModal!=="ticket")setTicketEvent(null);if(state.travelModal!=="style")setStyleEditorOpen(false);if(state.travelModal!=="font")setFontEditorOpen(false);if(state.travelModal!=="hero")setHeroEditorOpen(false);if(state.travelModal!=="login")setLoginOpen(false);if(state.travelModal!=="guide")setGuideId(null);setTab(state.travelTab||"plan");};window.addEventListener("popstate",handleBack);return()=>window.removeEventListener("popstate",handleBack);},[]);
  useEffect(()=>{if(tab==="edit"||dirty)return;const timer=window.setInterval(async()=>{try{const response=await fetch("/api/state",{cache:"no-store"});const raw=await response.json() as Partial<SharedState>;if(!raw.days?.length||!raw.hero||raw.version===sharedRef.current.version)return;const next={hero:raw.hero,days:raw.days,version:raw.version||0};const merged=mergeShared(sharedRef.current,overlayRef.current,next);sharedRef.current=next;if(!isAdmin)setData(current=>({...current,...merged,version:next.version}));}catch{}},8000);return()=>clearInterval(timer);},[tab,dirty,isAdmin]);
  useEffect(()=>{if(!ready)return;const timer=window.setTimeout(()=>{if(!isAdmin)overlayRef.current={hero:data.hero,days:data.days};void localPut({base:sharedRef.current,local:overlayRef.current,tickets:data.tickets,expenses:data.expenses});},250);return()=>clearTimeout(timer);},[data,ready,isAdmin]);

  const nextEventId=useMemo(()=>{if(!day)return undefined;if(selectedDate!==today)return day.events[0]?.id;const now=new Date().getHours()*60+new Date().getMinutes();return day.events.find(event=>getStartMinutes(event.time)>=now)?.id||day.events.at(-1)?.id;},[day,selectedDate,today]);
  function goTab(next:Tab){if(next===tab)return;history.pushState({...history.state,travelApp:true,travelTab:next},"");setTab(next);}
  function openModal(kind:"ticket"|"style"|"font"|"hero"|"login"|"guide",open:()=>void){history.pushState({...history.state,travelApp:true,travelTab:tab,travelModal:kind},"");open();}
  function openGuide(guide:AttractionGuide){openModal("guide",()=>setGuideId(guide.id));}
  function closeModal(fallback:()=>void){if(history.state?.travelModal)history.back();else fallback();}
  function previewTicket(ticket:Ticket){if(!ticket.fileData)return;history.pushState({...history.state,travelApp:true,travelTab:tab,travelModal:"ticket",travelPreview:true},"");setTicketPreview({data:ticket.fileData,type:ticket.fileType||"application/octet-stream",name:ticket.fileName||"票券"});}
  function mutateDays(updater:(days:DayPlan[])=>DayPlan[]){setData(current=>({...current,days:updater(current.days)}));setDirty(true);}
  function updateEvent(id:string,patch:Partial<EventItem>){mutateDays(days=>days.map(x=>x.date===selectedDate?{...x,events:x.events.map(e=>e.id===id?{...e,...patch}:e)}:x));}
  function addEvent(event:Omit<EventItem,"id">){mutateDays(days=>days.map(x=>x.date===selectedDate?{...x,events:[...x.events,{...event,id:crypto.randomUUID()}].sort((a,b)=>getStartMinutes(a.time)-getStartMinutes(b.time))}:x));}
  function removeEvent(id:string){mutateDays(days=>days.map(x=>x.date===selectedDate?{...x,events:x.events.filter(e=>e.id!==id)}:x));}
  async function applyStyle(styleTheme:DayStyle){setData(current=>({...current,hero:{...current.hero,styleTheme}}));if(!isAdmin)return;try{const shared={...sharedRef.current,hero:{...sharedRef.current.hero,styleTheme}};const response=await fetch("/api/state",{method:"PUT",headers:{"content-type":"application/json; charset=utf-8"},body:JSON.stringify({hero:shared.hero,days:shared.days})});if(!response.ok)throw new Error();const result=await response.json() as {version:number};sharedRef.current={...shared,version:result.version};setData(current=>({...current,version:result.version}));}catch{flash("風格自動儲存失敗，請稍後再試");}}
  async function saveAll(){setSaving(true);try{if(isAdmin){const response=await fetch("/api/state",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({hero:data.hero,days:data.days})});if(!response.ok)throw new Error();const result=await response.json();sharedRef.current={hero:data.hero,days:data.days,version:result.version};setData(x=>({...x,version:result.version}));flash("已發布，所有人的共用行程將自動更新");}else{overlayRef.current={hero:data.hero,days:data.days};await localPut({base:sharedRef.current,local:overlayRef.current,tickets:data.tickets,expenses:data.expenses});flash("已儲存在這台手機，不會影響其他人");}setDirty(false);}catch{flash("儲存失敗，請稍後再試");}finally{setSaving(false);}}
  async function logout(){await fetch("/api/auth/logout",{method:"POST"});setIsAdmin(false);const merged=mergeShared(sharedRef.current,overlayRef.current,sharedRef.current);setData(x=>({...x,...merged}));setDirty(false);flash("已回到個人模式");}
  const dayExpenses=data.expenses.filter(x=>x.date===selectedDate).reduce((s,x)=>s+x.amount,0),totalExpenses=data.expenses.reduce((s,x)=>s+x.amount,0);
  const globalStyle=data.hero.styleTheme||"peranakan";

  return <main className={`app-shell app-theme-${globalStyle}`} style={{"--font-scale":fontScale} as React.CSSProperties}>
    <header className={`hero compact hero-style-${globalStyle} ${data.hero.backgroundImage?"has-image":""}`} style={data.hero.backgroundImage?{backgroundImage:`var(--hero-overlay),url(${data.hero.backgroundImage})`}:undefined}><div className="hero-main"><div><p className="eyebrow">{data.hero.kicker}</p><h1>{data.hero.title}</h1></div>{tab==="edit"&&<button className="settings-button hero-settings" onClick={()=>openModal("hero",()=>setHeroEditorOpen(true))} aria-label="修改主畫面">⚙</button>}</div><div className="hero-footer"><div className="trip-meta"><span>{data.hero.tripDates}</span><span>{data.hero.hotel}</span></div><div className="hero-controls"><button className="settings-button style-main-button" onClick={()=>openModal("style",()=>setStyleEditorOpen(true))} aria-label="修改整體風格" title="修改整體風格">🎨</button><button className="settings-button font-main-button" onClick={()=>openModal("font",()=>setFontEditorOpen(true))} aria-label="調整文字大小" title="調整文字大小">Aa</button></div></div></header>
    <section className="date-section"><select id="date-select" aria-label="選擇行程日期" value={selectedDate} onChange={e=>setSelectedDate(e.target.value)}>{data.days.map((x,i)=><option value={x.date} key={x.id}>DAY {i+1} · {dateLabel(x.date)}（{x.weekday}）· {x.theme}{x.date===today?" · 今天":""}</option>)}</select></section>
    {tab==="plan"&&day&&<section className="content plan-view"><DayHeading day={day}/><div className="status-card"><span className="pulse"/><div><small>{selectedDate===today?"依照現在時間，下一站":"這一天的第一站"}</small><strong>{day.events.find(x=>x.id===nextEventId)?.title}</strong></div><button onClick={()=>eventRefs.current[nextEventId||""]?.scrollIntoView({behavior:"smooth",block:"center"})}>前往</button></div><div className="timeline">{day.events.map(event=>{const tickets=data.tickets.filter(x=>x.eventId===event.id),guide=guideForEvent(initialGuides,event.id);return <details key={event.id} ref={node=>{eventRefs.current[event.id]=node;}} className={`timeline-item ${event.id===nextEventId?"next":""}`}><summary><time>{event.time}</time><span className={`dot ${event.kind||"spot"}`}/><div><h3>{event.title}</h3><p>{event.note}</p></div><span className="chevron">⌄</span></summary><div className="event-actions icon-actions">{guide&&<button aria-label={`查看 ${guide.title} 景點介紹`} title="景點介紹" onClick={()=>openGuide(guide)}>🏛️</button>}{event.location&&<a aria-label="Google Maps 導航" title="Google Maps 導航" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(event.location)}`} target="_blank" rel="noreferrer">➤</a>}{tickets.length>0&&<button aria-label={`開啟 ${tickets.length} 張票券`} title="票券" onClick={()=>openModal("ticket",()=>setTicketEvent(event))}>🎟️</button>}<button aria-label="記一筆花費" title="記一筆花費" onClick={()=>goTab("expenses")}>💰</button></div></details>;})}</div></section>}
    {tab==="attractions"&&<Attractions guides={initialGuides} foods={foodGuides} openGuide={openGuide}/>}
    {tab==="expenses"&&<Expenses data={data} setData={setData} selectedDate={selectedDate} dayExpenses={dayExpenses} totalExpenses={totalExpenses} flash={flash}/>} 
    {tab==="edit"&&day&&<section className="content edit-view"><div className={`mode-card ${isAdmin?"admin":""}`}><div><small>{isAdmin?"ADMIN MODE":"PERSONAL MODE"}</small><strong>{isAdmin?"管理者共用編輯":"只修改這台手機"}</strong><p>{isAdmin?"儲存後會發布給所有使用者；他們自己的修改仍會保留。":"行程、票券與記帳只存於本機，不會影響其他人。"}</p></div>{isAdmin?<button className="secondary" onClick={logout}>登出</button>:<button className="secondary" onClick={()=>openModal("login",()=>setLoginOpen(true))}>管理者登入</button>}</div><Editor day={day} changeDate={date=>{const weekday=["日","一","二","三","四","五","六"][new Date(`${date}T12:00:00`).getDay()];mutateDays(days=>days.map(x=>x.id===day.id?{...x,date,weekday}:x));setSelectedDate(date);}} tickets={data.tickets} setTickets={tickets=>setData(x=>({...x,tickets}))} editingId={editingId} setEditingId={setEditingId} updateEvent={updateEvent} addEvent={addEvent} removeEvent={removeEvent} mutateDays={mutateDays} flash={flash} isAdmin={isAdmin}/></section>}
    <nav className="bottom-nav"><button className={tab==="plan"?"active":""} onClick={()=>goTab("plan")}><span>◷</span>行程</button><button className={tab==="attractions"?"active":""} onClick={()=>goTab("attractions")}><span>⌾</span>景點</button><button className={tab==="expenses"?"active":""} onClick={()=>goTab("expenses")}><span>$</span>記帳</button><button className={tab==="edit"?"active":""} onClick={()=>goTab("edit")}><span>✎</span>修改</button></nav>
    {tab==="edit"&&dirty&&<div className="save-dock"><span>有尚未儲存的修改</span><button className="primary" disabled={saving} onClick={saveAll}>{saving?"儲存中…":isAdmin?"發布給所有人":"儲存在這台手機"}</button></div>}
    {ticketEvent&&<TicketModal event={ticketEvent} tickets={data.tickets.filter(x=>x.eventId===ticketEvent.id)} preview={ticketPreview} openPreview={previewTicket} closePreview={()=>closeModal(()=>setTicketPreview(null))} close={()=>closeModal(()=>setTicketEvent(null))}/>} 
    {heroEditorOpen&&<HeroEditor hero={data.hero} isAdmin={isAdmin} setHero={hero=>{setData(x=>({...x,hero}));setDirty(true);}} close={()=>closeModal(()=>setHeroEditorOpen(false))} flash={flash}/>} 
    {loginOpen&&<LoginModal configured={configured} close={()=>closeModal(()=>setLoginOpen(false))} success={()=>{closeModal(()=>setLoginOpen(false));setIsAdmin(true);setData(x=>({...x,hero:sharedRef.current.hero,days:sharedRef.current.days,version:sharedRef.current.version}));setDirty(false);flash("已進入管理者模式");}}/>}
    {guideId&&<GuideModal guide={initialGuides.find(item=>item.id===guideId)!} close={()=>closeModal(()=>setGuideId(null))}/>}
    {styleEditorOpen&&<DayStyleModal selected={globalStyle} isAdmin={isAdmin} choose={styleTheme=>{void applyStyle(styleTheme);}} close={()=>closeModal(()=>setStyleEditorOpen(false))}/>}
    {fontEditorOpen&&<FontSizeModal selected={fontScale} choose={scale=>{setFontScale(scale);localStorage.setItem(FONT_SCALE_KEY,String(scale));}} close={()=>closeModal(()=>setFontEditorOpen(false))}/>}
    {toast&&<div className="toast">✓ {toast}</div>}
  </main>;
}

function DayHeading({day}:{day:DayPlan}){return <div className={`section-heading day-styled ${day.backgroundImage?"day-cover":""}`} style={day.backgroundImage?{backgroundImage:`var(--day-overlay),url(${day.backgroundImage})`}:undefined}><div><p>{dateLabel(day.date)} · 星期{day.weekday}</p><h2>{day.theme}</h2><span>{day.subtitle}</span></div></div>}

function Attractions({guides,foods,openGuide}:{guides:AttractionGuide[];foods:FoodGuide[];openGuide:(guide:AttractionGuide)=>void}){const [mode,setMode]=useState<"guide"|"food">("guide");useEffect(()=>{setMode(history.state?.exploreMode==="food"?"food":"guide");const handleBack=(event:PopStateEvent)=>setMode(event.state?.exploreMode==="food"?"food":"guide");window.addEventListener("popstate",handleBack);return()=>window.removeEventListener("popstate",handleBack);},[]);const showFood=()=>{history.pushState({...history.state,travelApp:true,travelTab:"attractions",exploreMode:"food"},"");setMode("food");};const showGuide=()=>{if(history.state?.exploreMode==="food")history.back();else setMode("guide");};return <section className="content feature-view attraction-view"><div className="explore-switch"><button className={mode==="guide"?"active":""} onClick={showGuide}>⌾ 景點導覽</button><button className={mode==="food"?"active":""} onClick={showFood}>🍜 美食天地</button></div>{mode==="guide"?<><div className="feature-title"><div><p>GUIDED VISITS · 依行程排序</p><h2>景點導覽</h2><span>點選景點後查看「簡介、歷史、順序導覽」</span></div></div><div className="attraction-list">{guides.map((guide,index)=><button className="attraction-card" key={guide.id} onClick={()=>openGuide(guide)}><span className="attraction-icon">{guide.icon}</span><div><small>STOP {String(index+1).padStart(2,"0")} · {dateLabel(guide.date)} · {guide.time}</small><h3>{guide.title}</h3><p>{guide.intro}</p></div><b>›</b></button>)}</div></>:<FoodWorld foods={foods}/>}</section>}

function GuideModal({guide,close}:{guide:AttractionGuide;close:()=>void}){const [section,setSection]=useState<"intro"|"history"|"tour">("intro");return <div className="modal-backdrop guide-backdrop"><section className="ticket-modal guide-modal"><div className="modal-title"><div className="guide-title"><span>{guide.icon}</span><div><small>{dateLabel(guide.date)} · {guide.time}</small><h2>{guide.title}</h2></div></div><button onClick={close} aria-label="關閉景點導覽">×</button></div><div className="guide-tabs"><button className={section==="intro"?"active":""} onClick={()=>setSection("intro")}>簡介</button><button className={section==="history"?"active":""} onClick={()=>setSection("history")}>歷史</button><button className={section==="tour"?"active":""} onClick={()=>setSection("tour")}>順序導覽</button></div><div className="guide-content">{section==="intro"&&<><h3>先認識這一站</h3><p>{guide.intro}</p></>}{section==="history"&&<><h3>歷史背景</h3><p>{guide.history}</p></>}{section==="tour"&&<><h3>跟著順序參觀</h3><ol>{guide.tourSteps.map((step,index)=><li key={`${guide.id}-${index}`}><span>{index+1}</span><p>{step}</p></li>)}</ol></>}<a className="guide-source" href={guide.sourceUrl} target="_blank" rel="noreferrer">參考資料：{guide.sourceLabel} ↗</a></div></section></div>}

function FoodWorld({foods}:{foods:FoodGuide[]}){return <><div className="feature-title food-heading"><div><p>SINGAPORE FLAVOURS</p><h2>美食天地</h2><span>價位為每人概估，實際菜單與營業時間以現場為準。</span></div></div><div className="food-list">{foods.map(food=><article className="food-card" key={food.id}><div className="food-card-head"><span>{food.icon}</span><div><small>{food.area}</small><h3>{food.name}</h3></div><b>{food.price}</b></div><p>{food.feature}</p><div className="dish-tags">{food.dishes.map(dish=><span key={dish}>{dish}</span>)}</div>{food.note&&<small className="food-note">提醒：{food.note}</small>}<a href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(food.location)}`} target="_blank" rel="noreferrer">➤ 開啟導航</a></article>)}</div></>}

function DayStyleModal({selected,isAdmin,choose,close}:{selected:DayStyle;isAdmin:boolean;choose:(style:DayStyle)=>void;close:()=>void}){return <div className="modal-backdrop style-backdrop"><section className="ticket-modal style-modal"><div className="modal-title"><div><small>APP STYLE</small><h2>選擇整體風格</h2></div><button onClick={close} aria-label="關閉風格選擇">×</button></div><p className="style-description">點選後會立即套用、自動儲存並關閉。{isAdmin?"管理者選擇會同步給所有人。":"只會保存在這台手機。"}</p><div className="style-options">{DAY_STYLE_OPTIONS.map(option=><button key={option.id} className={`style-option preview-${option.id} ${selected===option.id?"selected":""}`} onClick={()=>{choose(option.id);close();}}><span className="style-check">{selected===option.id?"✓":""}</span><small>{option.description}</small><strong>{option.sample}</strong><b>{option.name}</b></button>)}</div></section></div>}

function FontSizeModal({selected,choose,close}:{selected:number;choose:(scale:number)=>void;close:()=>void}){const options=[{value:.9,label:"較小"},{value:1,label:"標準"},{value:1.1,label:"大"},{value:1.2,label:"特大"},{value:1.3,label:"最大"}];return <div className="modal-backdrop"><section className="ticket-modal font-modal"><div className="modal-title"><div><small>TEXT SIZE · 本機設定</small><h2>調整文字大小</h2></div><button onClick={close} aria-label="關閉文字大小設定">×</button></div><p className="style-description">點選後立即套用並保存在這台手機；底部導覽維持固定大小。</p><div className="font-size-options">{options.map(option=><button key={option.value} className={selected===option.value?"selected":""} onClick={()=>{choose(option.value);close();}}><span style={{fontSize:`${16*option.value}px`}}>Aa</span><b>{option.label}</b>{selected===option.value&&<i>✓</i>}</button>)}</div><div className="font-preview" style={{fontSize:`${16*selected}px`}}><small>預覽文字</small><strong>今天前往濱海灣花園</strong><p>點開行程即可查看景點介紹、票券與導航。</p></div></section></div>}

function LoginModal({configured,close,success}:{configured:boolean;close:()=>void;success:()=>void}){const [username,setUsername]=useState("jimmy"),[password,setPassword]=useState(""),[error,setError]=useState(""),[loading,setLoading]=useState(false);async function submit(e:FormEvent){e.preventDefault();setLoading(true);setError("");const response=await fetch("/api/auth/login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({username,password})});if(response.ok)success();else setError((await response.json()).error||"登入失敗");setLoading(false);}return <div className="modal-backdrop"><section className="ticket-modal settings-modal"><div className="modal-title"><div><small>ADMIN</small><h2>管理者登入</h2></div><button onClick={close} aria-label="關閉">×</button></div>{!configured&&<p className="form-error">網站尚未設定管理者環境變數。</p>}<form className="form-grid" onSubmit={submit}><label className="wide">帳號<input autoComplete="username" value={username} onChange={e=>setUsername(e.target.value)}/></label><label className="wide">密碼<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<p className="form-error wide">{error}</p>}<button className="primary wide" disabled={loading||!configured}>{loading?"登入中…":"登入"}</button></form></section></div>}

function TicketModal({event,tickets,preview,openPreview,closePreview,close}:{event:EventItem;tickets:Ticket[];preview:TicketPreview|null;openPreview:(t:Ticket)=>void;closePreview:()=>void;close:()=>void}){return <div className="modal-backdrop"><section className="ticket-modal"><div className="modal-title"><div><small>MY TICKETS · 本機離線</small><h2>{event.title}</h2></div><button onClick={close} aria-label="關閉票券">×</button></div><div className="ticket-list">{tickets.map(ticket=><article className="ticket-card compact-ticket" key={ticket.id}><div className="ticket-top"><span>ADMIT ONE</span><b>已存於此裝置</b></div><p>{ticket.fileName||"票券"}</p>{ticket.fileData&&ticket.fileType?.startsWith("image/")&&<button className="ticket-image-button" onClick={()=>openPreview(ticket)} aria-label="放大票券圖片"><img src={ticket.fileData} alt={ticket.fileName||"票券圖片"}/></button>}{ticket.fileData&&!ticket.fileType?.startsWith("image/")&&<button className="file-link file-open-button" onClick={()=>openPreview(ticket)}>開啟檔案</button>}</article>)}</div></section>{preview&&<LocalFilePreview preview={preview} close={closePreview}/>}</div>}

function dataUrlToObjectUrl(dataUrl:string,mimeType:string){const comma=dataUrl.indexOf(",");if(comma<0)throw new Error("Invalid local file");const header=dataUrl.slice(0,comma),payload=dataUrl.slice(comma+1);const binary=header.includes(";base64")?atob(payload):decodeURIComponent(payload);const bytes=new Uint8Array(binary.length);for(let index=0;index<binary.length;index++)bytes[index]=binary.charCodeAt(index);return URL.createObjectURL(new Blob([bytes],{type:mimeType}));}

function LocalFilePreview({preview,close}:{preview:TicketPreview;close:()=>void}){const [objectUrl,setObjectUrl]=useState("");useEffect(()=>{let url="";try{url=dataUrlToObjectUrl(preview.data,preview.type);setObjectUrl(url);}catch{setObjectUrl("");}return()=>{if(url)URL.revokeObjectURL(url);};},[preview]);const isImage=preview.type.startsWith("image/");return <div className="file-lightbox"><div className="file-preview-header"><strong>{preview.name}</strong><button onClick={close} aria-label="關閉檔案預覽">×</button></div><div className="file-preview-stage">{isImage?<img className="preview-image" src={objectUrl||preview.data} alt={preview.name}/>:objectUrl?<iframe src={objectUrl} title={preview.name}/>:<p>檔案無法開啟，請重新加入票券。</p>}</div></div>}

function Expenses({data,setData,selectedDate,dayExpenses,totalExpenses,flash}:{data:AppData;setData:React.Dispatch<React.SetStateAction<AppData>>;selectedDate:string;dayExpenses:number;totalExpenses:number;flash:(s:string)=>void}){const [title,setTitle]=useState(""),[amount,setAmount]=useState("") ,[category,setCategory]=useState("餐飲");function add(e:FormEvent){e.preventDefault();if(!title||!Number(amount))return;setData(x=>({...x,expenses:[...x.expenses,{id:crypto.randomUUID(),date:selectedDate,title,amount:Number(amount),category}]}));setTitle("");setAmount("");flash("已記錄在這台手機");}return <section className="content feature-view"><div className="feature-title"><div><p>EXPENSES · 本機資料</p><h2>旅費記帳</h2><span>每個人的花費各自保存在自己的裝置</span></div></div><div className="money-grid"><article><small>當日花費</small><strong>{money.format(dayExpenses)}</strong></article><article className="dark"><small>總花費</small><strong>{money.format(totalExpenses)}</strong></article></div><form className="panel expense-form form-grid" onSubmit={add}><h3 className="wide">新增花費</h3><label>分類<select value={category} onChange={e=>setCategory(e.target.value)}><option>餐飲</option><option>門票</option><option>交通</option><option>購物</option><option>其他</option></select></label><label>金額（SGD）<input inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label className="wide">項目<input value={title} onChange={e=>setTitle(e.target.value)}/></label><button className="primary wide">加入</button></form><div className="panel expense-list">{data.expenses.filter(x=>x.date===selectedDate).map(x=><article key={x.id}><span>$</span><div><h3>{x.title}</h3><p>{x.category}</p></div><strong>{money.format(x.amount)}</strong><button onClick={()=>setData(d=>({...d,expenses:d.expenses.filter(e=>e.id!==x.id)}))}>×</button></article>)}</div></section>}

function Editor({day,changeDate,tickets,setTickets,editingId,setEditingId,updateEvent,addEvent,removeEvent,mutateDays,flash,isAdmin}:{day:DayPlan;changeDate:(s:string)=>void;tickets:Ticket[];setTickets:(t:Ticket[])=>void;editingId:string|null;setEditingId:(s:string|null)=>void;updateEvent:(id:string,p:Partial<EventItem>)=>void;addEvent:(e:Omit<EventItem,"id">)=>void;removeEvent:(id:string)=>void;mutateDays:(u:(d:DayPlan[])=>DayPlan[])=>void;flash:(s:string)=>void;isAdmin:boolean}){
  const [coverOpen,setCoverOpen]=useState(false);
  useEffect(()=>{setCoverOpen(false);},[day.id]);
  return <>
    <section className={`panel day-edit ${coverOpen?"open":""}`}>
      <button type="button" className="editor-section-toggle" aria-expanded={coverOpen} onClick={()=>setCoverOpen(open=>!open)}><span><strong>日期與當日封面</strong><small>{dateLabel(day.date)} · {day.theme}</small></span><b>{coverOpen?"⌃":"⌄"}</b></button>
      {coverOpen&&<div className="day-edit-fields"><label>日期<input type="date" value={day.date} onChange={e=>changeDate(e.target.value)}/></label><label>標題<input value={day.theme} onChange={e=>mutateDays(ds=>ds.map(x=>x.id===day.id?{...x,theme:e.target.value}:x))}/></label><label>副標題<input value={day.subtitle} onChange={e=>mutateDays(ds=>ds.map(x=>x.id===day.id?{...x,subtitle:e.target.value}:x))}/></label><BackgroundUploader current={day.backgroundImage} isAdmin={isAdmin} onUploaded={url=>mutateDays(ds=>ds.map(x=>x.id===day.id?{...x,backgroundImage:url}:x))} onClear={()=>mutateDays(ds=>ds.map(x=>x.id===day.id?{...x,backgroundImage:undefined}:x))} flash={flash}/></div>}
    </section>
    <div className="edit-list">{day.events.map(event=>{const open=editingId===event.id;const kindLabel=event.kind==="food"?"餐廳":event.kind==="transit"?"交通":event.kind==="rest"?"休息":"景點";return <article className={`edit-card ${open?"panel open":""}`} key={event.id}><button type="button" className="edit-card-toggle" aria-expanded={open} onClick={()=>setEditingId(open?null:event.id)}><time>{event.time}</time><span className={`dot ${event.kind||"spot"}`} aria-hidden="true"/><span className="edit-card-copy"><strong>{event.title}</strong><small>{kindLabel}{tickets.some(x=>x.eventId===event.id)?" · 有本機票券":""}</small></span><b className="chevron">⌄</b></button>{open&&<div className="edit-card-body"><div className="form-grid"><label>時間<input value={event.time} onChange={e=>updateEvent(event.id,{time:e.target.value})}/></label><label>類型<select value={event.kind} onChange={e=>updateEvent(event.id,{kind:e.target.value as EventItem["kind"]})}><option value="spot">景點</option><option value="food">餐廳</option><option value="transit">交通</option><option value="rest">休息</option></select></label><label className="wide">名稱<input value={event.title} onChange={e=>updateEvent(event.id,{title:e.target.value})}/></label><label className="wide">細節<textarea value={event.note} onChange={e=>updateEvent(event.id,{note:e.target.value})}/></label><label className="wide">Google Maps 地點<input value={event.location||""} onChange={e=>updateEvent(event.id,{location:e.target.value})}/></label></div><TicketAdmin event={event} tickets={tickets.filter(x=>x.eventId===event.id)} allTickets={tickets} setTickets={setTickets} flash={flash}/><div className="edit-actions"><button type="button" className="danger" onClick={()=>{removeEvent(event.id);setEditingId(null);}}>刪除行程</button><button type="button" className="primary" onClick={()=>setEditingId(null)}>收起修改</button></div></div>}</article>})}</div>
    <AddEventForm addEvent={addEvent}/>
  </>;
}

function AddEventForm({addEvent}:{addEvent:(e:Omit<EventItem,"id">)=>void}){const [open,setOpen]=useState(false),[time,setTime]=useState("09:00"),[title,setTitle]=useState(""),[note,setNote]=useState(""),[location,setLocation]=useState(""),[kind,setKind]=useState<EventItem["kind"]>("spot");if(!open)return <button className="primary" onClick={()=>setOpen(true)}>＋ 新增景點或餐廳</button>;return <form className="panel form-grid add-form" onSubmit={e=>{e.preventDefault();if(!title)return;addEvent({time,title,note,location,kind});setTitle("");setOpen(false);}}><h3 className="wide">新增行程</h3><label>時間<input value={time} onChange={e=>setTime(e.target.value)}/></label><label>類型<select value={kind} onChange={e=>setKind(e.target.value as EventItem["kind"])}><option value="spot">景點</option><option value="food">餐廳</option><option value="transit">交通</option><option value="rest">休息</option></select></label><label className="wide">名稱<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label className="wide">細節<textarea value={note} onChange={e=>setNote(e.target.value)}/></label><label className="wide">Google Maps 地點<input value={location} onChange={e=>setLocation(e.target.value)}/></label><div className="edit-actions wide"><button type="button" className="secondary" onClick={()=>setOpen(false)}>取消</button><button className="primary">加入行程</button></div></form>}

function HeroEditor({hero,setHero,close,flash,isAdmin}:{hero:HeroConfig;setHero:(h:HeroConfig)=>void;close:()=>void;flash:(s:string)=>void;isAdmin:boolean}){return <div className="modal-backdrop"><section className="ticket-modal settings-modal"><div className="modal-title"><div><small>HOME SETTINGS</small><h2>修改主畫面</h2></div><button onClick={close} aria-label="關閉">×</button></div><div className="form-grid"><label className="wide">主標題<input value={hero.title} onChange={e=>setHero({...hero,title:e.target.value})}/></label><label>英文小標<input value={hero.kicker} onChange={e=>setHero({...hero,kicker:e.target.value})}/></label><label>住宿標籤<input value={hero.hotel} onChange={e=>setHero({...hero,hotel:e.target.value})}/></label><label className="wide">日期標籤<input value={hero.tripDates} onChange={e=>setHero({...hero,tripDates:e.target.value})}/></label></div><BackgroundUploader current={hero.backgroundImage} isAdmin={isAdmin} onUploaded={url=>setHero({...hero,backgroundImage:url})} onClear={()=>setHero({...hero,backgroundImage:undefined})} flash={flash}/><button className="primary settings-done" onClick={close}>完成設定</button></section></div>}

function BackgroundUploader({current,onUploaded,onClear,flash,isAdmin}:{current?:string;onUploaded:(s:string)=>void;onClear:()=>void;flash:(s:string)=>void;isAdmin:boolean}){const [loading,setLoading]=useState(false);async function upload(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;setLoading(true);try{if(isAdmin){const form=new FormData();form.set("file",file);if(current)form.set("replaceUrl",current);const response=await fetch("/api/assets",{method:"POST",body:form});if(!response.ok)throw new Error();onUploaded((await response.json()).url);}else onUploaded(await fileToData(file));flash(isAdmin?"共用封面已上傳":"封面已儲存在這台手機");}catch{flash("圖片上傳失敗，請使用小於 4 MB 的圖片");}finally{setLoading(false);}}async function clear(){if(isAdmin&&current?.startsWith("/api/assets/"))await fetch(current,{method:"DELETE"}).catch(()=>undefined);onClear();}return <div className="background-control">{current&&<img src={current} alt="封面預覽"/>}<label className="secondary"><input type="file" accept="image/*" onChange={upload}/>{loading?"處理中…":current?"更換背景":"新增背景"}</label>{current&&<button className="danger" onClick={clear}>移除</button>}</div>}

function TicketAdmin({event,tickets,allTickets,setTickets,flash}:{event:EventItem;tickets:Ticket[];allTickets:Ticket[];setTickets:(t:Ticket[])=>void;flash:(s:string)=>void}){const [file,setFile]=useState<File|null>(null),[loading,setLoading]=useState(false);async function upload(e:FormEvent){e.preventDefault();if(!file)return flash("請選擇票券圖片或 PDF");if(file.size>12*1024*1024)return flash("單一檔案請小於 12 MB");setLoading(true);try{const ticket:Ticket={id:crypto.randomUUID(),eventId:event.id,name:file.name,number:"",fileName:file.name,fileType:file.type,fileData:await fileToData(file)};setTickets([...allTickets,ticket]);setFile(null);flash("票券已離線儲存在這台裝置");}catch{flash("票券儲存失敗");}finally{setLoading(false);}}return <div className="ticket-admin"><h3>我的離線票券</h3>{tickets.map(x=><div className="admin-ticket" key={x.id}><span>🎟️</span><div><b>{x.fileName||"票券"}</b><small>儲存在這台手機</small></div><button onClick={()=>setTickets(allTickets.filter(t=>t.id!==x.id))} aria-label="刪除票券">×</button></div>)}<form className="form-grid" onSubmit={upload}><label className="upload wide"><input type="file" accept="image/*,.pdf" onChange={e=>setFile(e.target.files?.[0]||null)}/><span>{file?file.name:"點選加入 QR Code、圖片或 PDF"}</span></label><button className="secondary wide" disabled={loading||!file}>{loading?"儲存中…":"儲存在這台手機"}</button></form></div>}
